require 'rake/clean'
require 'rubygems'
require 'rubygems/package_task'
require 'rdoc/task'
require 'cucumber'
require 'cucumber/rake/task'

MEDIATEC = 'bundle exec bin/mediatec'

###################################################

task :default => :default_test

###################################################

task :test_check do
     sh "rake test TEST=test/check_test.rb"     
end

task :test_search do
     sh "rake test TEST=test/search_test.rb"     
end

task :test_add_usr do
     sh "rake test TEST=test/add_usr_test.rb"     
end

task :test_add_film do
     sh "rake test TEST=test/add_film_test.rb"     
end

task :test_borrow do
     sh "rake test TEST=test/borrow_test.rb"     
end

task :test_return do
     sh "rake test TEST=test/return_test.rb"     
end

task :test_flux_user do
     sh "rake test TEST=test/flux_user_test.rb"     
end

task :test_flux_film do
     sh "rake test TEST=test/flux_film_test.rb"     
end

task :acceptation_check do
     sh "rake test_acceptation TEST=test_acceptation/check_test.rb"
end

task :acceptation_search do
     sh "rake test_acceptation TEST=test_acceptation/search_test.rb"
end

task :acceptation_add_film do
     sh "rake test_acceptation TEST=test_acceptation/add_film_test.rb"
end

task :acceptation_add_usr do
     sh "rake test_acceptation TEST=test_acceptation/add_usr_test.rb"
end

task :acceptation_borrow do
     sh "rake test_acceptation TEST=test_acceptation/borrow_test.rb"
end

task :acceptation_return do
     sh "rake test_acceptation TEST=test_acceptation/return_test.rb"
end

task :default_test do
     sh "rake test TEST=test/default_test.rb"     
end


###################################################

#####################################

Rake::RDocTask.new do |rd|
  rd.main = "README.rdoc"
  rd.rdoc_files.include("README.rdoc","lib/**/*.rb","bin/**/*")
  rd.title = 'Your application title'
end

spec = eval(File.read('mediatec.gemspec'))

Gem::PackageTask.new(spec) do |pkg|
end
CUKE_RESULTS = 'results.html'
CLEAN << CUKE_RESULTS
desc 'Run features'
Cucumber::Rake::Task.new(:features) do |t|
  opts = "features --format html -o #{CUKE_RESULTS} --format progress -x"
  opts += " --tags #{ENV['TAGS']}" if ENV['TAGS']
  t.cucumber_opts =  opts
  t.fork = false
end

desc 'Run features tagged as work-in-progress (@wip)'
Cucumber::Rake::Task.new('features:wip') do |t|
  tag_opts = ' --tags ~@pending'
  tag_opts = ' --tags @wip'
  t.cucumber_opts = "features --format html -o #{CUKE_RESULTS} --format pretty -x -s#{tag_opts}"
  t.fork = false
end

task :cucumber => :features
task 'cucumber:wip' => 'features:wip'
task :wip => 'features:wip'

require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/*_test.rb']
end

Rake::TestTask.new(:test_acceptation) do |t|
  t.libs << "test_acceptation"
  t.test_files = FileList['test_acceptation/*_test.rb']
end

task :default => [:test,:features]
